% 9.1
% Draw a graph of the population of the USA from 1790 to 2000, using the
% (logistic) model:
% P(t) = 197, 273, 000/(1 + e^?0.03134(t?1913.25))
% where t is the date in years.
% Actual data (in 1000s) for every decade from 1790 to 1950 are as follows:
% 3929, 5308, 7240, 9638, 12,866, 17,069, 23,192, 31,443, 38,558,
% 50,156, 62,948, 75,995, 91,972, 105,711, 122,775, 131,669, 150,697.
% Superimpose this data on the graph of P(t). Plot the data as discrete
% circles (i.e., do not join them with lines) as shown in Figure 9.16.

% 9.2
% The Spiral of Archimedes (Figure 9.17) may be represented in polar coordinates
% by the equation: r=a*theta
% where a is some constant. (The shells of a class of animals called nummulites
% grow in this way.) Write some command-line statements to draw
% the spiral for some values of a.

% a = input('what is a? ');
% x = 0:pi/40:4*pi;
% polar(x,a*x)

% 9.4
% The arrangement of seeds in a sunflower head (and other flowers,
% like daisies) follows a fixed mathematical pattern. The nth seed is at
% position: r=sqrt(n)
% with angular co-ordinate pi*d*n/180 radians, where d is the constant angle
% of divergence (in degrees) between any two successive seeds, i.e., between
% the nth and (n + 1)th seeds. A perfect sunflower head (Figure 9.18) is
% generated by d = 137.51°. Write a program to plot the seeds; use a circle
% (o) for each seed. A remarkable feature of this model is that the angle d
% must be exact to get proper sunflowers. Experiment with some different
% values, e.g., 137.45° (spokes, from fairly far out), 137.65° (spokes all the
% way), 137.92° (Catherine wheels).

% n = 1:1000;
% d = 137.51
% polar(pi*d*n./180, sqrt(n),'o')

% 9.5
% The equation of an ellipse in polar co-ordinates is given by:
% r = a(1 - e^2)/(1 - e*cos(theta))
% where a is the semi-major axis and e is the eccentricity, if one focus is at
% the origin, and the semi-major axis lies on the x-axis.
% Halley’s Comet, which visited us in 1985/6, moves in an elliptical orbit
% about the Sun (at one focus) with a semi-major axis of 17.9 A.U.
% (A.U. stands for Astronomical Unit, which is the mean distance of the
% Earth from the Sun: 149.6 million km.) The eccentricity of the orbit is
% 0.967276. Write a program which draws the orbit of Halley’s Comet and
% the Earth (assume the Earth is circular).

% a = 17.9;
% e = 0.967276;
% theta = 0:pi/80:2*pi;
% r = a*(1 - e^2)./(1 - e*cos(theta));
% polar(theta,r)

